### ISSUE TITLE
[bug] Some image formats trigger failures in PDF processing

### ISSUE THREAD

**Issue by triathematician** [aplpolaris/promptfx#328]
Example error:
```
org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
..
	at org.apache.pdfbox@3.0.2/org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:438)
	at tri.promptkt/tri.util.pdf.PdfUtils.images(PdfUtils.kt:103)
```

Occurs in PdfUtils `images()` method. This can be resolved with the following POM addition:
```
        <dependency>
            <groupId>com.github.jai-imageio</groupId>
            <artifactId>jai-imageio-core</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.jai-imageio</groupId>
            <artifactId>jai-imageio-jpeg2000</artifactId>
            <version>1.3.0</version>
        </dependency>
```

Should also make it so if an exception is thrown in this method it still returns what it can.

**Comment by triathematician** [comment]
License may be problematic for JJ2000 Library, see https://github.com/jai-imageio/jai-imageio-jpeg2000 -- adding the core library to the promptkt pom, but will leave JJ2000 out.
